# Site Settings
title: Blog
email: simon.vernin+jekyll@gmail.com
description: Un blog de tout et de rien
baseurl: "/jekyllblog" # the subpath of your site, e.g. /blog
url: "https://svernin.github.io/" # the base hostname & protocol for your site

# User Settings
username: SVernin
user_description: Etudiant souhaitant partager ses découvertes


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Accueil
    url: /
  - title: A propos
    url: /about/
  - title: Contact
    url: /contact/
  - title: Tags
    url: /tags/index.html

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
